name: Log Key Vault Secrets

on:
  workflow_dispatch: # manual trigger

jobs:
  log-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Fetch and log Key Vault secrets
        run: |
          SECRETS="${{ secrets.SECRETS_TO_READ }}"
          IFS=',' read -ra SECRET_ARRAY <<< "$SECRETS"
          for SECRET_NAME in "${SECRET_ARRAY[@]}"; do
            VALUE=$(az keyvault secret show --name "$SECRET_NAME" --vault-name "${{ secrets.KEY_VAULT_NAME }}" --query "value" -o tsv)
            echo "Secret $SECRET_NAME: $VALUE"
          done

