name: Log Key Vault Secrets

on:
  workflow_dispatch: # manual trigger

jobs:
  log-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Azure Key Vault Secrets
        id: azurekeyvault
        uses: Azure/get-keyvault-secrets@v1
        with:
         keyvault: KarthikVault
         secrets: ENVFROMKEYVAULT
         
      - name: Echo pulled secret
        run: echo ${{ steps.azurekeyvault.outputs.ENVFROMKEYVAULT }}

      - name: Save secret to file (temp debug only!)
        run: echo "${{ steps.azurekeyvault.outputs.ENVFROMKEYVAULT }}" > secret.txt

      - name: Show unmasked secret
        run: cat secret.txt

      - name: Upload secret file (dev only)
        uses: actions/upload-artifact@v3
        with:
         name: secret-file
         path: secret.txt
